/* Generated By:JavaCC: Do not edit this line. UriParserConstants.java */
package com.homesnap.webserver.rest.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UriParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HOUSE = 4;
  /** RegularExpression Id. */
  int CONTROLLER = 5;
  /** RegularExpression Id. */
  int CONTROLLERS = 6;
  /** RegularExpression Id. */
  int GROUP = 7;
  /** RegularExpression Id. */
  int GROUPS = 8;
  /** RegularExpression Id. */
  int LABEL = 9;
  /** RegularExpression Id. */
  int LABELS = 10;
  /** RegularExpression Id. */
  int NAME = 11;
  /** RegularExpression Id. */
  int VALUE = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int EOL = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"house\"",
    "\"controller\"",
    "\"controllers\"",
    "\"group\"",
    "\"groups\"",
    "\"label\"",
    "\"labels\"",
    "<NAME>",
    "<VALUE>",
    "<LETTER>",
    "<DIGIT>",
    "\"\\n\"",
    "\"/\"",
    "\"?id=\"",
    "\"?\"",
    "\"=\"",
    "\"&\"",
  };

}
