/* Generated By:JavaCC: Do not edit this line. UriParserConstants.java */
package com.homesnap.webserver.rest.parser;

/*
 * #%L
 * HomeSnapWebServer
 * %%
 * Copyright (C) 2011 - 2014 A. de Giuli
 * %%
 * This file is part of MyDomo done by A. de Giuli (arnaud.degiuli(at)free.fr).
 * 
 *     MyDomo is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     MyDomo is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with MyDomo.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UriParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HOUSE = 4;
  /** RegularExpression Id. */
  int CONTROLLER = 5;
  /** RegularExpression Id. */
  int CONTROLLERS = 6;
  /** RegularExpression Id. */
  int GROUP = 7;
  /** RegularExpression Id. */
  int GROUPS = 8;
  /** RegularExpression Id. */
  int LABEL = 9;
  /** RegularExpression Id. */
  int LABELS = 10;
  /** RegularExpression Id. */
  int NAME = 11;
  /** RegularExpression Id. */
  int VALUE = 12;
  /** RegularExpression Id. */
  int LETTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int EOL = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"house\"",
    "\"controller\"",
    "\"controllers\"",
    "\"group\"",
    "\"groups\"",
    "\"label\"",
    "\"labels\"",
    "<NAME>",
    "<VALUE>",
    "<LETTER>",
    "<DIGIT>",
    "\"\\n\"",
    "\"/\"",
    "\"?id=\"",
    "\"?\"",
    "\"=\"",
    "\"&\"",
  };

}
