package com.homesnap.engine.controller.heating;

import com.homesnap.engine.controller.what.StateName;

/**
 * Enumeration of state names for HeatingZone controller.
 * 
 * Generated by ControllerStateGenerator
 */
public enum HeatingZoneStateName implements StateName {
	
	STATUS,
	SET_TEMPERATURE_HEATING,
	SET_TEMPERATURE_CONDITIONAL,
	SET_TEMPERATURE_GENERIC,
	MEASURE_TEMPERATURE,
	LOCAL_OFFSET;
	
	@Override
	public String getName() {
		return name().toLowerCase();
	}
}
