package com.homesnap.engine.controller.gateway;

import com.homesnap.engine.controller.what.StateName;

/**
 * Enumeration of state names for Gateway controller.
 * 
 * Generated by ControllerStateGenerator
 */
public enum GatewayStateName implements StateName {
	
	DATE,
	DATETIME,
	DISTRIBUTION_VERSION,
	FIRMWARE_VERSION,
	IP_ADDRESS,
	KERNEL_VERSION,
	MAC_ADDRESS,
	MODEL,
	NETMASK,
	TIME,
	UPTIME;
	
	@Override
	public String getName() {
		return name().toLowerCase();
	}
}
