/* Generated By:JavaCC: Do not edit this line. UriParserConstants.java */
package com.homesnap.webserver.servlet.house.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UriParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HOUSE = 4;
  /** RegularExpression Id. */
  int CONTROLLER = 5;
  /** RegularExpression Id. */
  int CONTROLLERS = 6;
  /** RegularExpression Id. */
  int GROUP = 7;
  /** RegularExpression Id. */
  int GROUPS = 8;
  /** RegularExpression Id. */
  int LABEL = 9;
  /** RegularExpression Id. */
  int LABELS = 10;
  /** RegularExpression Id. */
  int ON = 11;
  /** RegularExpression Id. */
  int OFF = 12;
  /** RegularExpression Id. */
  int UP = 13;
  /** RegularExpression Id. */
  int DOWN = 14;
  /** RegularExpression Id. */
  int STOP = 15;
  /** RegularExpression Id. */
  int ID = 16;
  /** RegularExpression Id. */
  int EOL = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"house\"",
    "\"controller\"",
    "\"controllers\"",
    "\"group\"",
    "\"groups\"",
    "\"label\"",
    "\"labels\"",
    "\"on\"",
    "\"off\"",
    "\"up\"",
    "\"down\"",
    "\"stop\"",
    "<ID>",
    "\"\\n\"",
    "\"/\"",
    "\"?id=\"",
    "\"?what=on\"",
    "\"?what=off\"",
  };

}
