/* Generated By:JavaCC: Do not edit this line. CommandParserConstants.java */
package com.adgsoftware.mydomo.engine.connector.openwebnet.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CommandParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAL = 4;
  /** RegularExpression Id. */
  int EOL = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<VAL>",
    "\"\\n\"",
    "\"*#\"",
    "\"*\"",
    "\"##\"",
    "\"**\"",
    "\"#\"",
    "\"#4#\"",
  };

}
