package com.homesnap.engine.controller.automation;

import com.homesnap.engine.controller.what.StateName;

/**
 * Enumeration of state names for Automation controller.
 * 
 * Generated by ControllerStateGenerator
 */
public enum AutomationStateName implements StateName {
	
	STATUS;
	
	@Override
	public String getName() {
		return name().toLowerCase();
	}
}
