/* Generated By:JavaCC: Do not edit this line. UriParserConstants.java */
package com.homesnap.webserver.rest.recorder.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UriParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RECORDER = 4;
  /** RegularExpression Id. */
  int NAME = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int VALUE = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int EOL = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"recorder\"",
    "<NAME>",
    "<NUMBER>",
    "<VALUE>",
    "<LETTER>",
    "<DIGIT>",
    "\"\\n\"",
    "\"/\"",
    "\"?\"",
    "\"=\"",
    "\"&\"",
  };

}
