package com.homesnap.engine.controller.light.legrand;

import com.homesnap.engine.controller.what.StateName;

/**
 * Enumeration of state names for LightLegrand controller.
 * 
 * Generated by ControllerStateGenerator
 */
public enum LightLegrandStateName implements StateName {
	
	/** Contains all state names of the Legrand implementation Light controller. */
	STATUS;
	
	@Override
	public String getName() {
		return name().toLowerCase();
	}
}
