package com.homesnap.engine.controller.clock;

import com.homesnap.engine.controller.what.StateName;

/**
 * Enumeration of state names for ClockSensor controller.
 * 
 * Generated by ControllerStateGenerator
 */
public enum ClockSensorStateName implements StateName {
	
	ALARM,
	DATE,
	DATE_TIME,
	TIME;
	
	@Override
	public String getName() {
		return name().toLowerCase();
	}
}
