package com.homesnap.engine.controller.light;

/*
 * #%L
 * HomeSnapEngine
 * %%
 * Copyright (C) 2011 - 2014 A. de Giuli
 * %%
 * This file is part of HomeSnap done by Arnaud de Giuli (arnaud.degiuli(at)free.fr)
 *     helped by Olivier Driesbach (olivier.driesbach(at)gmail.com).
 * 
 *     HomeSnap is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     HomeSnap is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with HomeSnap. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */


import com.homesnap.engine.controller.what.StateName;

/**
 * Enumeration of state names for Light controller.
 * 
 * Generated by ControllerStateGenerator
 */
public enum LightStateName implements StateName {
	
	/** Contains the hexadecimal color code for RGB devices. */
	COLOR,
	/** Contains the current level of light for dimmable devices. */
	LEVEL,
	/** Defines how long the light stays on before being off when status is set to blinking and has no effect otherwise. */
	BLINK_TIME,
	/** Contains the current status of the light (ie: on, off, blinking ...) depending on vendor capabilities. */
	STATUS;
	
	@Override
	public String getName() {
		return name().toLowerCase();
	}
}
