package com.homesnap.engine.controller.light;

import com.homesnap.engine.controller.what.StateName;

/**
 * Enumeration of state names for Light controller.
 * 
 * Generated by ControllerStateGenerator
 */
public enum LightStateName implements StateName {
	
	/** Contains the hexadecimal color code for RGB devices. */
	COLOR,
	/** Contains the current level of light for dimmable devices. */
	LEVEL,
	/** Defines how long the light stays on before being off when status is set to blinking and has no effect otherwise. */
	BLINK_TIME,
	/** Contains the current status of the light (ie: on, off, blinking ...) depending on vendor capabilities. */
	STATUS;
	
	@Override
	public String getName() {
		return name().toLowerCase();
	}
}
