package com.homesnap.engine.controller.what.impl;

/*
 * #%L
 * HomeSnapEngine
 * %%
 * Copyright (C) 2011 - 2014 A. de Giuli
 * %%
 * This file is part of HomeSnap done by Arnaud de Giuli (arnaud.degiuli(at)free.fr)
 *     helped by Olivier Driesbach (olivier.driesbach(at)gmail.com).
 * 
 *     HomeSnap is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     HomeSnap is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with HomeSnap. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */


import com.homesnap.engine.controller.what.State;
import com.homesnap.engine.controller.what.impl.UpDownState.UpDownValue;

/**
 * Enumeration of the possible values of the state name {@link AutomationStateName#STATUS}.
 * 
 * Generated by ControllerStateGenerator
 */
public class UpDownState implements State<UpDownValue> {
	
	public UpDownState(UpDownValue value) {
		setValue(value);
	}

	private UpDownValue value;
	
	@Override
	public UpDownValue getValue() {
		return value;
	}

	@Override
	public void setValue(UpDownValue value) {
		this.value = value;
	}
	
	public enum UpDownValue {
		UP,
		DOWN,
		STOP;
	}

	@Override
	public void fromString(String value) {
		this.value = UpDownValue.valueOf(value);
	}
	
	@Override
	public String toString() {
		return value.name();
	}
}
